### ISSUE TITLE
XDFWriter Unity

### ISSUE THREAD

**Issue by LMBooth** [labstreaminglayer/LSL4Unity#41]
Hi all,

I'm currently combining data from a custom EEG device and pupil labs via the LSL in Unity for live gaze tracking and object recognition. I can't seem to find an xdfwriter for C#, would i be best pulling the function out of the LabRecorder C++ files and creating a custom DLL for Unity, (i'm new to c++ so unsure if this is possible or how much work it would take) or exporting all the streams from unity to the LabRecorder or a custom Python script? (It would be nice if i could keep it all contained within Unity.) 

Regards,

Liam

**Comment by cboulay** [comment]
Hi Liam, that isn't how LSL is supposed to work. I'm going to close this issue because it isn't really something to be solved by LSL or LSL4Unity. But we can continue to discuss your particular needs.

I think it might be more efficient to setup your framework a different way.

* Unity shouldn't be a requirement to use your EEG device. The simplest and most flexible solution would be to make a simple application (could be C# if you want) that reads data from your device and streams it out over LSL. If you want to use C++ then please see the [AppTemplate](https://github.com/labstreaminglayer/AppTemplate_cpp_qt).
* With the pupil-labs LSL plugin, you also get their data as an LSL stream.
* Your Unity application will also have to an output an LSL stream of markers for events and possibly other streams if it has continuously sampled data (e.g., state of an object).
* LabRecorder will pick up these streams, and write them to xdf including sufficient information to synchronize them later.

So then how do you get your gaze and EEG data into Unity?
* For the gaze data you _could_ use LSL-C# and the pupil-labs LSL stream if you really wanted to but you can also use pupil-labs Unity connectors (hmd-eyes I think?) which will give you some other features like in-Unity calibration.
* For the EEG data, you can use LSL-C#. However, unless you intend to use the raw data from your device in Unity, I think a more common approach is to use a different process to read in the EEG stream, do your signal processing, then output a new LSL stream of processed features, and it's this feature stream that you will read in Unity. You'll have a much easier time processing your data in Matlab or Python than in C#.

The main advantages of this approach is that you will have access to the entire LSL ecosystem, including applications like LabRecorder which is actively maintained, signal processing tools in Matlab or Python (e.g., MNE-Python, Neuropype), visualizers, etc. Also, this modular approach makes it easier to swap out components (e.g., keep everything the same but swap out the experiment, or swap out the EEG headset if sharing your experiment with a collaborator who does not have your device).

I hope that's clear.

**Comment by LMBooth** [comment]
Thank you for the speedy response! That's fine to close the issue if its inappropriate.

I currently have my EEG LSL stream open on the computer, (I modified the NeuroscanAcquire package to suit my data and i can see the waveforms in LSL viewers - seems to be correct), so i'd be best not even receiving this in to Unity and just take it right to the LabRecorder?

I originally used the HMD-Eyes in Unity but my thinking for synchronised data between the eye tracking and EEG led me to the LSL package. I'm currently able to calculate the estimated users gaze from the LSL pupil stream by using the same methodology as the HMD-eyes package. So i should turn my new meta data (or markers) regarding my unity scene in to a new stream and capture all 3 streams in LabRecorder for the EEG device, Pupil labs and Unity information?

**Comment by cboulay** [comment]
> so i'd be best not even receiving this in to Unity and just take it right to the LabRecorder?

Do you need it in Unity? Are you manipulating the experiment or the stimuli using neurofeedback? If not then you are correct, and the EEG stream never needs to be touched in Unity.

> I'm currently able to calculate the estimated users gaze from the LSL pupil stream by using the same methodology as the HMD-eyes package

It's up to you whether you use HMD-eyes or LSL in Unity to get the gaze data. A year or so ago, there was a big difference between the two. Now the data are the same. The main difference now is that HMD-Eyes gives you some tools for calibration, etc. You can use HMD-Eyes in Unity and use the LSL-Plugin in LabRecorder. Regardless of which you use in Unity, note that there can be a discrepancy in the recorded data and the effective behaviour in Unity. For example, if someone passes through an object with a saccade, it's possible that the LSL data sampled at 200 Hz will register a sample in the object, but Unity sampling at the framerate (~90 Hz in an HMD) will not register a sample in the object. So an offline analysis might suggest an object should have been triggered when in fact it wasn't in Unity. For this reason and more, you should make sure to stream Unity events so that you have a ground truth as to what actually happened (and what the subject observed) in Unity.

> So i should turn my new meta data (or markers) regarding my unity scene in to a new stream and capture all 3 streams in LabRecorder for the EEG device, Pupil labs and Unity information?

Yes!

**Comment by LMBooth** [comment]
Excellent, that makes much more sense now. No doubt i'll be returning for help when it comes to doing some live signal processing later creating neurofeedback, for now i'm interested in post analysis (hence the want for a xdf writer).

Thank you for the heads up regarding possible discrepancies from saccades, for the unity event stream what sort of event information would you recommend streaming, (user HMD positions constantly, or only when they interact with the scene?)

**Comment by cboulay** [comment]
If you're using a SteamVR headset or something otherwise OpenVR compatible then you can use [this](https://github.com/labstreaminglayer/App-OpenVR) to continuously stream head pose, controller poses, and controller inputs.

I'm not sure if Pupil's new routines offer online saccade detection. If they do then use that. If not then I strongly recommend against rolling your own saccade detector (it could be a months long project and yield minimal value).

Other than the above, I recommend streaming an event marker for anything perceptible to the user (appearance of an instruction, appearance of a target, a reward indicator, a sound, etc) and for any useful demarcations in the data even if they are imperceptible (e.g., 'PreStimulusDelay' event at 1 s before the stimulus) because they could make offline analysis easier, or even future online analysis easier (collect baseline data now!).

**Comment by LMBooth** [comment]
That's great to keep in mind in my developments, thanks again for your help Chadwick.
