### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by gregbci** [labstreaminglayer/LSL4Unity#52]
Hello,

I'm getting a DLLNotFoundException with LSL4Unity on a mac (m1 / arm64).  I can reproduce it in a new Unity project with LSL4Unity installed.  Bringing up LSL editor menu triggers the error:

<img width="992" alt="Screenshot 2023-07-25 at 4 23 31 PM" src="https://github.com/labstreaminglayer/LSL4Unity/assets/114951757/d5b170d6-5af7-4a66-abac-bf3303182341">

Looking at the installed LSL4Unity package in my Unity project, I can see that it's missing the DLL symlinks for `Plugins/LSL/macOS/arm64`.  The links are present in the [LSL4Unity](https://github.com/labstreaminglayer/LSL4Unity/tree/master/Plugins/LSL/macOS/arm64) repo, so Unity probably doesn't support them / create them.

If I recreate the links and reimport, then the problem is fixed.  I noticed the linux plugin has copies instead of symlinks, which might have been a workaround to this issue?  I'd be happy to make a PR to fix this, just wanted to check that I'm not missing something.

**Comment by cboulay** [comment]
It certainly worked at one point. That's a shame that the symlinks didn't survive.

So yeah, please go ahead with a PR. I don't think we need 3 copies of the dylib. I don't remember the thought process behind that in the Linux variant. I think we can just drop the symlinks and have the Unity plugin directly link the true dylib we keep.

Which filename do we give the kept dylib? The one with the fully qualified version, then we have to go into the Unity code to update the links everytime we change the dylib version? Or to the unqualified liblsl.dylib, and then we have the possibility of forgetting which version of the dylib we're bundling?

I think the former (fully qualified name) is OK because I think we have to go into the Unity code _anyway_ whenever there's a dylib update, because we have to set some flags on the file or something. My memory on that is hazy.

**Comment by gregbci** [comment]
The unqualified name is used in [LSL.cs](https://github.com/labstreaminglayer/LSL4Unity/blob/a3096a95c8de3bcfb2ff2216e7607ed1b2efd642/Runtime/LSL.cs#L897).  If we stuck with that, I don't think a code change would be needed for a liblsl update, just drop in the new libs.  Libsls for Windows ships as just "lsl.lib" already.

That said, I also like seeing the fully qualified version in the repo.  So, for the want of a few megabytes, I say just copy all three as was done on the Linux side.

I'll put the PR together today.

**Comment by cboulay** [comment]
> The unqualified name is used in [LSL.cs](https://github.com/labstreaminglayer/LSL4Unity/blob/a3096a95c8de3bcfb2ff2216e7607ed1b2efd642/Runtime/LSL.cs#L897)

Of course. Sorry I forgot about that.
Your solution sounds good. I look forward to the PR. Thanks!

**Comment by gregbci** [comment]
K, will do.  @cboulay I need repo access to create a branch / PR

**Comment by cboulay** [comment]
I think a typical gitflow for this circumstance is to fork and create a PR from the fork. I could probably setup access to this repo but I'd need to add in some protections first. The fork pathway is faster for now.

**Comment by gregbci** [comment]
K will do, thanks!
